### PR TITLE
[core] Try to fix #1144 by hook

### LINKED ISSUE #1144: [Bug] fatal err when hook zygoteSendArgsAndGetResult
### Steps to reproduce/复现步骤

**ENV**  
Device: Pixe4
ROM:[11.0.0 (RQ3A.210905.001, Sep 2021)](https://developers.google.com/android/images#flame)
Magisk: 23.0 
Riru: v26.1.2.r505.c20529bced
Riru-LSPosed: v1.5.3(5984）

---------------------
**Reproduce**
Dev module to hook android.os.ZygoteProcess.zygoteSendArgsAndGetResult：
```java
    public void handleLoadPackage(XC_LoadPackage.LoadPackageParam loadPackageParam) throws Throwable {
        if (!loadPackageParam.packageName.equals("android")) return;

        XposedHelpers.findAndHookMethod("android.os.ZygoteProcess", classLoader, "zygoteSendArgsAndGetResult", "android.os.ZygoteProcess$ZygoteState", int.class, "java.util.ArrayList", new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
            }
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                Object result = param.getResult();
            }
        });
    }
```

### Expected behaviour/预期行为

nothing happened

### Actual behaviour/实际行为

wait for a while（2min in average)
then system_server keep crash.

**Cause Guessing**
1. May be attributed to some optimization procedures on R. (art::ProfilingInfo::GetInlineCache)
2. And the demo worked well on Android Q（Framework SDK 29）

### Xposed Module List/Xposed 模块列表

```shell
this dev demo only
```

### Magisk Module List/Magisk 模块列表

```shell
MagiskFrida:15.1.1-1
MagiskHide Props Config:v6.0.2-v132
Riru: v26.1.2.r505.c20529bced
Riru-LSPosed: v1.5.3(5984）
```

### LSPosed version/LSPosed 版本

v1.5.3(5984）

### Android version/安卓版本

11

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

v26.1.2.r505.c20529bced

### CI Version/CI 版本

- [X] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

[LSPosed_2021-09-19T13_13_44.451.zip](https://github.com/LSPosed/LSPosed/files/7191100/LSPosed_2021-09-19T13_13_44.451.zip)
[LSPosed_2021-09-19T13_38_03.206.zip](https://github.com/LSPosed/LSPosed/files/7191101/LSPosed_2021-09-19T13_38_03.206.zip)

### PR DESCRIPTION
**Pull request by yujincheng08**

### CODE REVIEW

File: core/src/main/cpp/main/include/art/runtime/jit/profiling_info.h [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+                    break;
+                case __ANDROID_API_O_MR1__:
+                    [[fallthrough]];
+                case __ANDROID_API_P__:
+                    [[fallthrough]];
+                case __ANDROID_API_R__:
+                    [[fallthrough]];
+                case __ANDROID_API_S__:
+                    if constexpr(lspd::is64) {
+                        OFFSET_art_method = 64;
```
Comment (canyie) [inline core/src/main/cpp/main/include/art/runtime/jit/profiling_info.h:55]: 64? wtf

**Review by canyie — CHANGES_REQUESTED** [review]

**Review by canyie — APPROVED** [review]
lgtm, hope it works
