### PR TITLE
Skip new launch when the previous one is still pending

### LINKED ISSUE #2346: [Bug] Unable to launch manager via secret code
### Steps to reproduce/复现步骤

- Open dialer
- Input `#*#*5776733#*#*`

https://user-images.githubusercontent.com/24606814/213187612-dcb4dd40-226a-4cfe-8d3a-dab957972e45.mp4

Unable to reproduce every time, it happends randomly.

### Expected behaviour/预期行为

Open the parasitic manager.

### Actual behaviour/实际行为

Bugreport dialog was shown.

### Xposed Module List/Xposed 模块列表

```shell
- None
```

### Magisk Module List/Magisk 模块列表

```shell
- LSPosed
```

### LSPosed version/LSPosed 版本

v1.8.6 (6712)

### Android version/Android 版本

Android 13 (Oneplus 8 OxygenOS 13 F.13)

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```
01-17 14:25:54.244  1699  1743 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[org.lsposed.manager.LAUNCH_MANAGER] flg=0x10000000 pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity mCallingUid=0} from uid 1000
01-17 14:25:54.244  1699  1743 D LSPosed Bridge: activity from com.android.shell with Intent { act=android.intent.action.MAIN cat=[org.lsposed.manager.LAUNCH_MANAGER] pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity mCallingUid=0 } with extras null is starting
01-17 14:25:54.245   973  2928 D LSPosedService: checking manager intent
01-17 14:25:54.245   973  2928 D LSPosedService: starting target app of parasitic manager
01-17 14:25:54.245   973  2928 D LSPosedService: requesting launch of manager
01-17 14:25:54.245   973  2928 D LSPosedService: requested to launch manager
01-17 14:25:54.252  1699  1743 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[org.lsposed.manager.LAUNCH_MANAGER] flg=0x10000000 pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity mCallingUid=0} from uid 1000
01-17 14:25:54.252  1699  1743 D LSPosed Bridge: activity from com.android.shell with Intent { act=android.intent.action.MAIN cat=[org.lsposed.manager.LAUNCH_MANAGER] pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity mCallingUid=0 } with extras null is starting
01-17 14:25:54.253   973  2928 D LSPosedService: checking manager intent
01-17 14:25:54.253   973  2928 D LSPosedService: starting target app of parasitic manager
01-17 14:25:54.253   973  2928 D LSPosedService: requesting launch of manager
01-17 14:25:54.253   973  2928 D LSPosedService: requested to launch manager
01-17 14:25:54.309   973  2928 D LSPosedService: stopped old package
01-17 14:25:54.310  1699  5276 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[0f6cc700-0830-4e16-8795-90cd692fbe50,org.lsposed.manager.LAUNCH_MANAGER] flg=0x10000000 pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity mCallingUid=0} from uid 1000
01-17 14:25:54.310  1699  5276 D LSPosed Bridge: activity from com.android.shell with Intent { act=android.intent.action.MAIN cat=[0f6cc700-0830-4e16-8795-90cd692fbe50,org.lsposed.manager.LAUNCH_MANAGER] pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity mCallingUid=0 } with extras null is starting
01-17 14:25:54.310   973  2928 D LSPosedService: checking manager intent
01-17 14:25:54.310   973  2928 D LSPosedService: starting target app of parasitic manager
01-17 14:25:54.310   973  2928 D LSPosedService: requesting launch of manager
01-17 14:25:54.310   973  2928 D LSPosedService: manager is still running or is on its way
01-17 14:25:54.323   973  2928 D LSPosedService: relaunching
01-17 14:25:54.337  1706  1707 D LSPosed : zygisk_main.cpp:362#void lspd::CompanionEntry(int): Got cache with fd=5 size=24
01-17 14:25:54.338 15854 15854 D LSPosed : symbol_cache.cpp:55#void lspd::InitSymbolCache(lspd::SymbolCache *): InitSymbolCache
01-17 14:25:54.338 15854 15854 D LSPosed : symbol_cache.cpp:57#void lspd::InitSymbolCache(lspd::SymbolCache *): Already initialized
01-17 14:25:54.356  1699  5276 D LSPosed Bridge: onTransact: action=ACTION_GET_BINDER, callingUid=2000, callingPid=15854
01-17 14:25:54.357   973 10077 D LSPosedService: starting injected manager: pid = 15854 uid = 2000 processName = com.android.shell
01-17 14:25:54.357   973 10077 D LSPosedService: returned service
01-17 14:25:54.357   973 10077 D LSPosedService: register ProcessInfo{uid=2000, pid=15854, processName='com.android.shell', heartBeat=android.os.BinderProxy@b74941f}
01-17 14:25:54.357  1699  5276 D LSPosed Bridge: got binder is android.os.BinderProxy@c01830d
01-17 14:25:54.357   973 10077 D LSPosedService: LSPApplicationService.onTransact: code=1310096052
01-17 14:25:54.357 15854 15854 D LSPosed : service.cpp:327#std::tuple<int, size_t> lspd::Service::RequestLSPDex(JNIEnv *, const ScopedLocalRef<jobject> &): fd=77, size=974080
01-17 14:25:54.357   973 10077 D LSPosedService: LSPApplicationService.onTransact: code=724533732
01-17 14:25:54.358 15854 15854 D LSPosed : service.cpp:357#std::map<std::string, std::string> lspd::Service::RequestObfuscationMap(JNIEnv *, const ScopedLocalRef<jobject> &): android.app.AndroidApp => android.app.AndroidApp
01-17 14:25:54.358 15854 15854 D LSPosed : service.cpp:357#std::map<std::string, std::string> lspd::Service::RequestObfuscationMap(JNIEnv *, const ScopedLocalRef<jobject> &): android.content.res.XModule => android.content.res.XModule
01-17 14:25:54.358 15854 15854 D LSPosed : service.cpp:357#std::map<std::string, std::string> lspd::Service::RequestObfuscationMap(JNIEnv *, const ScopedLocalRef<jobject> &): android.content.res.XRes => android.content.res.XRes
01-17 14:25:54.358 15854 15854 D LSPosed : service.cpp:357#std::map<std::string, std::string> lspd::Service::RequestObfuscationMap(JNIEnv *, const ScopedLocalRef<jobject> &): de.robv.android.xposed. => de.robv.android.xposed.
01-17 14:25:54.358 15854 15854 D LSPosed : service.cpp:357#std::map<std::string, std::string> lspd::Service::RequestObfuscationMap(JNIEnv *, const ScopedLocalRef<jobject> &): org.lsposed.lspd.core. => org.lsposed.lspd.core.
01-17 14:25:54.358 15854 15854 D LSPosed : service.cpp:357#std::map<std::string, std::string> lspd::Service::RequestObfuscationMap(JNIEnv *, const ScopedLocalRef<jobject> &): org.lsposed.lspd.nativebridge. => org.lsposed.lspd.nativebridge.
01-17 14:25:54.358 15854 15854 D LSPosed : service.cpp:357#std::map<std::string, std::string> lspd::Service::RequestObfuscationMap(JNIEnv *, const ScopedLocalRef<jobject> &): org.lsposed.lspd.service. => org.lsposed.lspd.service.
01-17 14:25:54.358 15854 15854 D LSPosed : context.cpp:35#lspd::Context::PreloadedDex::PreloadedDex(int, std::size_t): Context::PreloadedDex::PreloadedDex: fd=77, size=974080
01-17 14:25:54.372   973 10077 D LSPosedService: ProcessInfo{uid=2000, pid=15854, processName='com.android.shell', heartBeat=android.os.BinderProxy@b74941f} is dead
01-17 14:25:54.379   973  2928 D LSPosedService: stopped old package
01-17 14:25:54.382  1699  4391 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[4f2984b1-e2cc-4366-8e98-ca92e77b1efc,org.lsposed.manager.LAUNCH_MANAGER] flg=0x10000000 pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity mCallingUid=0} from uid 1000
01-17 14:25:54.382  1699  4391 D LSPosed Bridge: activity from com.android.shell with Intent { act=android.intent.action.MAIN cat=[4f2984b1-e2cc-4366-8e98-ca92e77b1efc,org.lsposed.manager.LAUNCH_MANAGER] pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity mCallingUid=0 } with extras null is starting
01-17 14:25:54.383   973  2928 D LSPosedService: checking manager intent
01-17 14:25:54.383   973  2928 D LSPosedService: starting target app of parasitic manager
01-17 14:25:54.383   973  2928 D LSPosedService: requesting launch of manager
01-17 14:25:54.383   973  2928 D LSPosedService: manager is still running or is on its way
01-17 14:25:54.393   973  2928 D LSPosedService: relaunching
01-17 14:25:54.401  1706  1707 D LSPosed : zygisk_main.cpp:362#void lspd::CompanionEntry(int): Got cache with fd=5 size=24
01-17 14:25:54.401 16081 16081 D LSPosed : symbol_cache.cpp:55#void lspd::InitSymbolCache(lspd::SymbolCache *): InitSymbolCache
01-17 14:25:54.401 16081 16081 D LSPosed : symbol_cache.cpp:57#void lspd::InitSymbolCache(lspd::SymbolCache *): Already initialized
01-17 14:25:54.418  1699  4391 D LSPosed Bridge: onTransact: action=ACTION_GET_BINDER, callingUid=2000, callingPid=16081
01-17 14:25:54.418   973 10077 D LSPosedService: Skipped com.android.shell/2000
01-17 14:25:54.419 16081 16081 D LSPosed : magisk_loader.cpp:231#void lspd::MagiskLoader::OnNativeForkAndSpecializePost(JNIEnv *, jstring): skipped com.android.shell
```

### PR DESCRIPTION
**Pull request by libxzr**
Fixes #2346

### CODE REVIEW

File: daemon/src/main/java/org/lsposed/lspd/service/LSPManagerService.java [hunk 1]
```diff
@@ -263,6 +263,12 @@ synchronized boolean preStartManager(String pkgName, Intent intent) {
                     // or it's run by ourself after killing, resume it
                     return true;
                 } else {
+                    // Check the flag in case new launch comes before finishing
+                    // the previous one to avoid racing.
+                    if (pendingManager) {
+                        Log.d(TAG, "manager is still on its way when new launch comes, skipping");
+                        return false;
+                    }
```
Comment (yujincheng08) [inline daemon/src/main/java/org/lsposed/lspd/service/LSPManagerService.java:271]:
```suggestion
                } else if (pendingManager) {
                    // Check the flag in case new launch comes before finishing
                    // the previous one to avoid racing.
                    Log.d(TAG, "manager is still on its way when new launch comes, skipping");
                    return false;
                } else {
```

**Review by aviraxp — APPROVED** [review]
